### ISSUE TITLE
Build fails to minify the code from React Scoped. 

### ISSUE THREAD

**Issue by Minaz123** [doxiaodong/react-scoped#1]
Hello.
I am trying to build my react project on the server (Which runs fine locally). and i get the following error.
Pls note that it was running fine earlier before the react-scoped module was added. 

Failed to minify the code from this file:

        ./node_modules/react-scoped/lib/ReactScoped.js:7

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! efendibey-website@0.1.0 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the efendibey-website@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-04T06_24_50_394Z-debug.log
Failed to Build the app

I have  node v8.3.0 and npm  v5.5.1 on the server. 

What can the issue be ?

Thank you.

**Comment by digiklug** [comment]
Hi, 
I am also facing the same issue any help would be appreciated. I put the error log below if that might help. Thanks.

0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v8.3.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v8.3.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.5.1
3 info using node@v8.3.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle eb-website@0.1.0~prebuild: eb-website@0.1.0
6 info lifecycle eb-website@0.1.0~build: eb-website@0.1.0
7 verbose lifecycle eb-website@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle eb-website@0.1.0~build: PATH: /root/.nvm/versions/node/v8.3.0/lib/node_modules/npm/bin/node-gyp-bin:/var/www/eb.dk.com/eb_website_main/node_modules/.bin:/root/.nvm/versions/node/v8.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle eb-website@0.1.0~build: CWD: /var/www/eb.dk.com/eb_website_main
10 silly lifecycle eb-website@0.1.0~build: Args: [ '-c', 'node scripts/build.js' ]
11 silly lifecycle eb-website@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle eb-website@0.1.0~build: Failed to exec build script
13 verbose stack Error: eb-website@0.1.0 build: `node scripts/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v8.3.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v8.3.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid eb-website@0.1.0
15 verbose cwd /var/www/eb.dk.com/eb_website_main
16 verbose Linux 3.10.0-514.10.2.el7.x86_64
17 verbose argv "/root/.nvm/versions/node/v8.3.0/bin/node" "/root/.nvm/versions/node/v8.3.0/bin/npm" "run" "build"
18 verbose node v8.3.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error eb-website@0.1.0 build: `node scripts/build.js`
22 error Exit status 1
23 error Failed at the eb-website@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by doxiaodong** [comment]
Sorry for late, I don't watch this repo before.
I will publish es5 code in npm soon.
@Minaz123 @digiklug

**Comment by doxiaodong** [comment]
https://github.com/doxiaodong/react-scoped/commit/cf3bfce10a1bd998eff88f3484ed963b1e3e6391

and release 1.0.0-beta.2

BTW, I'm glad to introduce https://github.com/Front-End-Engineering-Cloud/builder for you to replace create-react-app. The examples/ of this repo is use that, and the docs/ is the result of build
